import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { branding } from "@/lib/branding";

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 10, fontFamily: "Helvetica" },
  title: { fontSize: 18, marginBottom: 2 },
  subtitle: { fontSize: 10, color: "#666", marginBottom: 20 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 13, marginBottom: 6, borderBottom: "1px solid #ccc", paddingBottom: 3 },
  row: { flexDirection: "row", borderBottom: "1px solid #eee", paddingVertical: 4 },
  cell: { flex: 1 },
  empty: { color: "#999", fontStyle: "italic" },
  footer: { position: "absolute", bottom: 24, left: 32, right: 32, fontSize: 8, color: "#999" },
});

type Property = {
  name: string;
  address_line1: string | null;
  city: string | null;
  region: string | null;
  property_type: string;
};

type Asset = {
  name: string;
  manufacturer: string | null;
  model_number: string | null;
  serial_number: string | null;
};

type RecordRow = {
  occurred_on: string;
  title: string;
  cost: number | null;
  record_types: { label: string } | null;
};

type Warranty = { provider: string; expires_on: string };

type Expense = { expense_date: string; amount: number; tax_amount: number; category: string };

export function PropertyReportDocument({
  property,
  assets,
  records,
  warranties,
  expenses,
  generatedAt,
}: {
  property: Property;
  assets: Asset[];
  records: RecordRow[];
  warranties: Warranty[];
  expenses: Expense[];
  generatedAt: string;
}) {
  const expenseTotal = expenses.reduce((sum, expense) => sum + expense.amount + expense.tax_amount, 0);
  const address = [property.address_line1, property.city, property.region].filter(Boolean).join(", ");

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.title}>{property.name}</Text>
        <Text style={styles.subtitle}>
          {address || "No address on file"} -- {property.property_type.replace("_", " ")}
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Assets ({assets.length})</Text>
          {assets.length === 0 && <Text style={styles.empty}>None recorded.</Text>}
          {assets.map((asset, index) => (
            <View style={styles.row} key={index}>
              <Text style={styles.cell}>{asset.name}</Text>
              <Text style={styles.cell}>{asset.manufacturer ?? ""}</Text>
              <Text style={styles.cell}>{asset.model_number ?? ""}</Text>
              <Text style={styles.cell}>{asset.serial_number ?? ""}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>History ({records.length})</Text>
          {records.length === 0 && <Text style={styles.empty}>None recorded.</Text>}
          {records.map((record, index) => (
            <View style={styles.row} key={index}>
              <Text style={styles.cell}>{record.occurred_on}</Text>
              <Text style={styles.cell}>{record.record_types?.label ?? ""}</Text>
              <Text style={{ ...styles.cell, flex: 2 }}>{record.title}</Text>
              <Text style={styles.cell}>{record.cost ? `$${record.cost}` : ""}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Warranties ({warranties.length})</Text>
          {warranties.length === 0 && <Text style={styles.empty}>None recorded.</Text>}
          {warranties.map((warranty, index) => (
            <View style={styles.row} key={index}>
              <Text style={styles.cell}>{warranty.provider}</Text>
              <Text style={styles.cell}>Expires {warranty.expires_on}</Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            Expenses ({expenses.length}) -- Total ${expenseTotal.toFixed(2)}
          </Text>
          {expenses.length === 0 && <Text style={styles.empty}>None recorded.</Text>}
          {expenses.map((expense, index) => (
            <View style={styles.row} key={index}>
              <Text style={styles.cell}>{expense.expense_date}</Text>
              <Text style={styles.cell}>{expense.category}</Text>
              <Text style={styles.cell}>${(expense.amount + expense.tax_amount).toFixed(2)}</Text>
            </View>
          ))}
        </View>

        <Text style={styles.footer}>
          Generated by {branding.productName} on {generatedAt}. Does not include private notes or
          documents unless explicitly listed above.
        </Text>
      </Page>
    </Document>
  );
}
